- name: install and run nginx
  hosts: frontned
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start and enable nginx
    ansible.builtin.service:
      name: started
      state: present
      enabled: yes

    