- name: print the course information
  hosts: local
  connection: local
  vars:
    DURATION: 120
    COURSE: Ansible
    IS_LIVE: true
  TOOLS:
  - Linux
  - Shell
  - Ansible
  - Terraform
  CONCEPTS:
    CI: Jenkins
    SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: course information
    ansible.builtin.debug:
      msg: "duration is: {{ DURATION }}, cource is: {{ COURSE }}, is_live?: {{ IS_LIVE }}, tools are: {{ TOOLS }}, concepts are: {{ CONCEPTS }}" 